### ISSUE TITLE
Let's add a Materials category 

### ISSUE THREAD

**Issue by looeee** [pmndrs/market#1]
Hey guys! Really happy to see this repo spring to life! 

When I spoke with @drcmda a couple of weeks ago we talked about some way of sharing pre-made materials for prototyping. Things like metals, bricks, concrete, wood planks, and so on, all optimized for Three.js. 

There are two ways materials are usually shared - either as a texture pack, or as a complete surface. The texture pack is easy, you just put the maps in a zip file (you also have to get/create the textures, of ccourse). 

However, this doesn't capture other surface settings like refraction ratio, color, transparency, normal scale, etc.

I like what you're doing with the JSX code snippet beside the model download, we could do the same for the materials:

``` js
const [tex, roughnessTex, normalTex] = useLoader(THREE.TextureLoader, [texURL, roughnessTexURL, normalTexURL])

<mesh
	  <boxGeometry attach="geometry" args={[0.6, 0.6, 0.6]} />
	  <meshStandardMaterial attach="material" 
		    map={tex}
		    roughnessMap={roughnessTex}
		    normalMap={normalTex}
		    transparent 
		    opacity="0.25"
		    // ... etc.
	  />
/>
```

This does tie everything in to R3F quite strongly though. What about adding plain JS beside the JSX? 

P.S. I know that donut! 😆 
https://market-phi.vercel.app/model/donut

**Comment by SaraVieira** [comment]
I would love this, I can make a material category and ping you on discord on how to add your own materials, this sounds like an amazing idea!


We can definitely start by using some from cc0 materials
