### ISSUE TITLE
Able to drag Leva window under text

### ISSUE THREAD

**Issue by alii** [pmndrs/market#20]
It can't be dragged back again as the text eats the click event. Is it possible to disable dragging on Leva entirely?

https://user-images.githubusercontent.com/25351731/118467883-1d07db00-b6fc-11eb-9ed4-eadf71a1c1e1.mov

**Comment by SaraVieira** [comment]
Hey!

Thank you so much for catching that! Just removed the ability to drag here https://github.com/pmndrs/market/commit/df2c3fb17fc65507cb832c33dcb7861026395f35

Anything else feel free to make issues :)

**Comment by alii** [comment]
Awesome 🚀
