### ISSUE TITLE
Download MatCap Error

### ISSUE THREAD

**Issue by matthewbcool** [pmndrs/market#25]
Clicking "Download MapCap" results in a 500. Direct link works great. 

https://market.pmnd.rs/material/undefined
![Screen Shot 2021-05-18 at 12 34 57 PM](https://user-images.githubusercontent.com/4493657/118712358-8f002300-b7d5-11eb-98bb-6f11d6d9c4dc.png)

**Comment by SaraVieira** [comment]
Thank you for catching this.

Fixed in https://github.com/pmndrs/market/commit/8d1f4ddb160e1c63629a8e0da43e309836368fcb
