### ISSUE TITLE
Some of the vehicles have reversed faces

### ISSUE THREAD

**Issue by robhawkes** [pmndrs/market#29]
I couldn't find a "report issue" or similar on the new market site (which is amazing btw) so I'm posting here instead. Do let me know if I should report this somewhere else.

### Description
- Some vehicles have inside-out wheels and other faces (eg. sides of fire truck)

### Expectation
- No faces should be inside out on vehicles

### Specs
- Windows 10
- Chrome 90.0.4430.212 (Official Build) (64-bit)

#### [Firetruck](https://market.pmnd.rs/model/firetruck)
![image](https://user-images.githubusercontent.com/22612/118786221-80734380-b889-11eb-81da-d999dcbf5e43.png)

#### [Delivery Truck](https://market.pmnd.rs/model/delivery-truck)
![image](https://user-images.githubusercontent.com/22612/118786426-b44e6900-b889-11eb-81f1-7594cdbf7e4b.png)

### Examples without issue
- Some vehicles don't have this issue, though use similar / identical wheels

#### [Police Car](https://market.pmnd.rs/model/police-car)
![image](https://user-images.githubusercontent.com/22612/118786622-e9f35200-b889-11eb-83e7-f2061a1a6871.png)

#### [SUV](https://market.pmnd.rs/model/suv)
![image](https://user-images.githubusercontent.com/22612/118786739-07c0b700-b88a-11eb-8fc6-32bb47ea9bb9.png)

**Comment by robhawkes** [comment]
As an aside; I've visited some of these pages a few times now and the "Views" count for the Fire Truck is still on 0.

**Comment by SaraVieira** [comment]
The views uses the fathom api so it's not super real time ahaha

It's mostly for the order on the homepage

Gotta start turning on the back face thing on blender when doing these things :/

Will fix these in blender today. Great catch

**Comment by robhawkes** [comment]
Super quick reply, thanks @SaraVieira!

I make 3D geospatial visualisations and am [currently creating a framework around that in r3f](https://twitter.com/robhawkes/status/1394437168278421504), so very interested in the vehicle and building models; well and the trees and stuff too actually. Basically all of it 😅

I'll submit a couple of requests for models I'd love to see in a library like this (aircraft, etc). It would be great to have some documentation / a style guide on how to create models in the same low-poly style and same scale system, so I can try creating and submitting my own (want to explore Blender more anyway).

**Comment by SaraVieira** [comment]
The firetruck and delivery trucks are done, something is up with the cache of the second one but when downloaded it's fixed, it will update eventually 🤷🏻‍♀️

About the style a lot of the low poly styles were created by kenney,https://kenney.nl/ so I don't really have a styleguide or anything.

Yes! Do it :)

Please try to download both the models to make sure they work :)

**Comment by SaraVieira** [comment]
So what happened is that I forgot to push lol

Fixed: https://market.pmnd.rs/model/delivery-truck

**Comment by robhawkes** [comment]
Thanks for fixing those! And also for the link to Kenney's site — a proper goldmine that I'll be digging through.

You're going to hate me now but a few of the other vehicles also have the same problem with the flipped faces; I should have been more obvious in the original ticket. Sorry!

I just went through the other vehicles and these ones also have flipped faces on the wheels:
- [Garbage Truck](https://market.pmnd.rs/model/garbage-truck)
- [Hatchback](https://market.pmnd.rs/model/hatchback)
- [Sedan](https://market.pmnd.rs/model/sedan)
- [Sports Sedan](https://market.pmnd.rs/model/sports-sedan)
- [Luxury SUV](https://market.pmnd.rs/model/suv-luxury)
- [Tractor](https://market.pmnd.rs/model/tractor)
- [Tractor 2](https://market.pmnd.rs/model/tractor-2)
- [Police Tractor](https://market.pmnd.rs/model/tractor-police)

**Comment by SaraVieira** [comment]
Reopened to fix those tomorrow

**Comment by SaraVieira** [comment]
ufff, all done! Will create a mnaster issue for when an issue is found with any model and link it on the pages :)

Thank you!
