### ISSUE TITLE
Add a matcaps category, maybe?

### ISSUE THREAD

**Issue by looeee** [pmndrs/market#3]
Matcaps are great for prototyping and I've seen them in a number of production projects too. 

There are loads of matcaps here: 
https://github.com/nidorx/matcaps

According to the readme on that repo, the matcaps were gathered from various sources and are not the work of the repo owner. So it should be fine for us to co-host them here if we like.

**Comment by gsimone** [comment]
We are gathering a bunch of ideas for this and matcaps are included, do you want to hop on discord and help us brainstorm about it?

**Comment by SaraVieira** [comment]
This will be my first thing today

Get Renders and download links, will link straight to github I think using https://raw.githack.com/

I do wanna get some better renders of them

**Comment by SaraVieira** [comment]
Link for me in future reference: https://github.com/nidorx/matcaps/blob/master/PAGE-1.md

**Comment by SaraVieira** [comment]
This has been added in the live website 🔥
