### ISSUE TITLE
UserMenu hidden by other elements 

### ISSUE THREAD

**Issue by BrandonEscamilla** [pmndrs/market#34]
The UserMenu is hidden by other elements, it's not a problem until you are into "request an asset page" and the logout button is hidden. 

I think is a z-index fix, let me know if I can contribute, at least with these
small issues

![ex](https://user-images.githubusercontent.com/21966716/119029238-ff41ac80-b96d-11eb-8002-6aa576218d86.png)

**Comment by SaraVieira** [comment]
Oh sorry about that, did not see you wanted to contribute :/
