### ISSUE TITLE
Clean up all info components

### ISSUE THREAD

**Issue by SaraVieira** [pmndrs/market#40]
Right now we have three different info components:

- src/components/MaterialInfo.js
- src/components/ModelInfo.js
- src/components/HDRIInfo.js

Even though all of these are basically the same, this could easily be only one component that showed the buttons by the type of asset it is

**Comment by njm222** [comment]
I can take this... seems pretty straightforward. Anything else I should know about?

**Comment by SaraVieira** [comment]
I don't think so, ping me if you have any issues :)
