### ISSUE TITLE
Push Info Component to the top

### ISSUE THREAD

**Issue by SaraVieira** [pmndrs/market#42]
At the moment the sidebar in the individual assets feels kinda buggy because leva only shows up a couple of seconds after

Pushing it to the top would be a great addition
<img width="944" alt="Screenshot_2021-05-20_at_10 53 50" src="https://user-images.githubusercontent.com/1051509/119327945-d2e6a280-bc83-11eb-87f9-3c916bfd560d.png">

A page that is already doing something similar is the request page, the title is inserted there and not in the layout

**Comment by matheusmazeto** [comment]
I will check this.

**Comment by matheusmazeto** [comment]
@SaraVieira, do you want to put the Leva component on top? Or the entire ModelInfo component to the top?
And in what way exactly at the top? Next to the title (Ambulance)?

**Comment by SaraVieira** [comment]
The whole info thing in the sidebar, the leva part is filling a div so it's all html

**Comment by matheusmazeto** [comment]
Okay so, I'm going to try to move the entire ModelInfo component and the Leva that is inside it to the top, it will be positioned almost in the header and next to the Title (ambulance), I will follow it according to the red outline in the image you made above .

**Comment by matheusmazeto** [comment]
@SaraVieira Could you help me understand why the Model component is not stretching across its entire space?

If I remove the div around the Model component, it starts to grow infinitely, have you seen it happen?

![ambulance](https://user-images.githubusercontent.com/15149242/119723489-dfb1f480-be43-11eb-981a-fa1362a91a3c.png)

`<Layout noTitle>
      <main className='mb-10 grid grid-cols-2 sm:grid sm:grid-cols-3 gap-x-4 gap-y-8'>
        <div className='min-w-full min-h-full col-span-2'>
          <div className='mb-5'>
            <h1 className={'text-3xl font-bold leading-tight text-gray-900 '}>
              {title}
            </h1>
          </div>
          <div className='flex flex-1 min-w-full min-h-full col-span-2'>
            <Viewer {...model} />
          </div>
        </div>
        <ModelInfo {...model} />
      </main>
      <Stats stats={model.stats} size={model.size} />
      <NextAndPrev {...model} />
    </Layout>`

**Comment by matheusmazeto** [comment]
I'm a little absent due to personal problems, if anyone can take this issue feel free.

**Comment by SaraVieira** [comment]
@matheusmazeto Someone did but I hope things are better now
