### ISSUE TITLE
Bad URLs in copied JSX Scene Graph

### ISSUE THREAD

**Issue by mattrossman** [pmndrs/market#57]
The URL produced after clicking "Copy JSX Scene Graph" on a model contains a leading slash, which causes an error if you paste it into your project.

E.g. the scene graph copied for [the avacado](https://market.pmnd.rs/model/avocado) is:
``` jsx
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(
    '/https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/avocado/model.gltf'
  )
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.avocado.geometry}
        material={materials.brownDarkest}
        scale={[0.53, 0.53, 0.53]}
      />
    </group>
  )
}

useGLTF.preload(
  '/https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/avocado/model.gltf'
)

```

By contrast, the URL produced when clicking "Copy Primitive Import" is correct.

**Comment by mattrossman** [comment]
Looks like `asset.file` has the correct URL, so maybe this is an issue with gltfjsx

**Comment by njm222** [comment]
Yes I think you are correct, it's an issue with `gltfjsx`. 

When running `gltfjsx` one of the options is
` --root, -r       Sets directory from which .gltf file is served`
So it doesn't handle links

**Comment by drcmda** [comment]
ive fixed it in gltfjsx, looking for the presence of http. could anyone update? theres also a breaking change, the parser is not a default export any longer.

**Comment by SaraVieira** [comment]
Uhhhh

Will update today!

Thank you all!!
