### ISSUE TITLE
Thumbnails flicker rapidly when mousing over labels

### ISSUE THREAD

**Issue by CodyJasonBennett** [pmndrs/market#61]
Running on Firefox, Windows, I'm noticing that the hover transition is played rapidly while mousing over labels.

This stops when no longer mousing over a thumbnail and can persist while the cursor is still.

![hover-state](https://user-images.githubusercontent.com/23324155/121444299-e1f07480-c954-11eb-83b6-a1e0755ffd97.gif)

**Comment by SaraVieira** [comment]
Hey!

I think it's fixed, tested on my windows machine, and changing the z-index seems to have fixed it.

Also added a link to the category

**Comment by CodyJasonBennett** [comment]
I can confirm that this has been fixed on my end.

Thank you.
