### ISSUE TITLE
Problem using the browser of a mobile device 

### ISSUE THREAD

**Issue by Angelk90** [pmndrs/market#62]
Hi @SaraVieira, using the browser of a mobile device I get this:

![20210611_162006](https://user-images.githubusercontent.com/20476002/121722026-33c80480-cae5-11eb-8d41-d7dad9ad03a1.jpg)

Maybe it's a project related problem: https://github.com/pmndrs/leva

**Comment by SaraVieira** [comment]
Hey

Interesting because you are not supposed to get Leva in the mobile version :/

Can you tell me what your phone is? Or the screen size?

I get this one mine

![image](https://user-images.githubusercontent.com/1051509/121735459-72b28600-caf6-11eb-8e2a-2994b1943754.png)
****

**Comment by Angelk90** [comment]
@SaraVieira : I tried on two different devices a tablet or a mobile phone but I get the one shown in the picture.

**Comment by SaraVieira** [comment]
Do you know the screen size of them?

**Comment by Angelk90** [comment]
@SaraVieira :  Resolution | 800x1280 pixels

**Comment by SaraVieira** [comment]
I was only triggering at like 900, this should not show in any mobile device, so now after 1200 it disappears since it has no space
