### ISSUE TITLE
Editor button to go back 

### ISSUE THREAD

**Issue by Angelk90** [pmndrs/market#63]
Hi @SaraVieira, in edit materials the back button does not seem to work.
First I'm on this page:
https://market.pmnd.rs/model/dogue
Then I click on the "Edit materials" button and I am in this page:
https://market.pmnd.rs/editor/dogue

When I try to go back it doesn't work.

<img width="189" alt="Schermata 2021-06-11 alle 19 58 05" src="https://user-images.githubusercontent.com/20476002/121730257-bbb30c00-caef-11eb-9d4e-ecbb448a992a.png">

**Comment by SaraVieira** [comment]
Fixed in the commit linked, weird, the router from next was returning null
