### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Angelk90** [pmndrs/market#69]
Hi @SaraVieira , it would be interesting to also have the possibility to use the site in a dark mode version.

**Comment by Angelk90** [comment]
@SaraVieira :

https://user-images.githubusercontent.com/20476002/122668464-77430280-d1b8-11eb-8fb1-27d9256cbfcf.mov

<img width="1242" alt="Schermata 2021-06-20 alle 11 07 09" src="https://user-images.githubusercontent.com/20476002/122668299-adcc4d80-d1b7-11eb-8b2c-422639ab8fbb.png">
<img width="1308" alt="Schermata 2021-06-20 alle 11 07 00" src="https://user-images.githubusercontent.com/20476002/122668301-af961100-d1b7-11eb-9084-243ee89cdee7.png">

In dark mode, there are the following problems:
- As you can see from the video, you don't see the text inside the input field.
- Borders are missing, not only in the screenshots I posted.

P.s.
Personally I would recommend a different color for dark mode, too dark.

**Comment by SaraVieira** [comment]
Hey!

Fixed the above mentioned things and also changed the color to gray-900 instead of pure black
