### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by Angelk90** [pmndrs/market#70]
Hi @SaraVieira , it would be interesting to also have the possibility of having the multilingual site.
Example: Spanish, Italian, German etc.

**Comment by SaraVieira** [comment]
Hey

Since the website does not have a lot of text and it's nearly a side project this is not something I would like to do for now

**Comment by Angelk90** [comment]
@SaraVieira : I think when there is more text, there will be more work to be done, but they are choices.
