### ISSUE TITLE
Website dead, supabase DB is down?

### ISSUE THREAD

**Issue by GoreStarry** [pmndrs/market#98]
Since like supabase can't be accessed anymorem and I can't find the `button/model.gltf` in prepo, I really need that button, somebody please save me 🥹🙏.

**Comment by SaraVieira** [comment]
Hey!

Idk why but supabase paused the project

It's fixed!

**Comment by GoreStarry** [comment]
Thanks for saving my life~😭🙏

**Comment by shahriyardx** [comment]
Dead again

**Comment by SaraVieira** [comment]
Yeah it was supabase again, I don't know how I can make it not pause it without changing it pro

**Comment by SaraVieira** [comment]
Supabase is on pro so this will not happen again!
