### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by shahriyardx** [pmndrs/market#99]
the website is not working now. it keeps loading

**Comment by SaraVieira** [comment]
Fixed! Sorry about that

**Comment by rafalm1** [comment]
It is working but nothing is loading.

**Comment by brandonkylely** [comment]
I've been checking the site, seems like it's been down for the last 24 hours. Any updates?

**Comment by SaraVieira** [comment]
Yes! 

So it is back up but because of how the free plan on supabase works it may happen again 

I am talking to supabase rn to see if that project can get a pro plan

**Comment by shahriyardx** [comment]
> Yes!
> 
> So it is back up but because of how the free plan on supabase works it may happen again
> 
> I am talking to supabase rn to see if that project can get a pro plan

How can I selfhost this website? Any guide?
Because cloning and running it gives some error

**Comment by SaraVieira** [comment]
Right now it requires supabase :/

I don't know if I can export all the data from there BUT I know you can self host supabase

**Comment by SaraVieira** [comment]
Okay we are on pro :D
